export const data = [
    { id: 1,
      img: './img/joker3.jpg',
      tittle: 'Joker',
      link: "/video",
    },
    { id: 2,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 3,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 4,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 5,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 6,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 7,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 8,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 9,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 10,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 11,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 12,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 13,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 14,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 15,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 16,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 17,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 18,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 19,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 20,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 21,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 22,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 23,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 24,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 25,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 26,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 27,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 28,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 29,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 30,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 31,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
    { id: 32,
      img: './img/joker3.jpg',
      tittle: 'Joker',
    },
  ];
  
  export default data;